version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: notifications-mongodb
    ports:
      - "27017:27017"
    environment:
      # Задаем логин и пароль администратора root
      - MONGO_INITDB_ROOT_USERNAME=rootadmin
      - MONGO_INITDB_ROOT_PASSWORD=supersecretpassword
      # Указываем имя создаваемой базы данных
      - MONGO_INITDB_DATABASE=notificationsdb
    volumes:
      - mongo-data:/data/db
    networks:
      - notifications-network

  tasks-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifications-backend
    ports:
      - "8093:8093"
    environment:
      - SERVER_PORT=8093
      # Передаем логин и пароль в строке подключения (URI)
      # Имя переменной должно совпадать с тем, что написано в application.properties
      - MONGO_URI=mongodb://rootadmin:supersecretpassword@mongodb:27017/notificationsdb?authSource=admin

    depends_on:
      - mongodb
    networks:
      - notifications-network

volumes:
  mongo-data:

networks:
  tasks-network:
    driver: bridge