version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: tasks-mongodb
    ports:
      - "27017:27017"
    environment:
      # Задаем логин и пароль администратора root
      - MONGO_INITDB_ROOT_USERNAME=muser
      - MONGO_INITDB_ROOT_PASSWORD=mpass
      # Указываем имя создаваемой базы данных
      - MONGO_INITDB_DATABASE=tasks_db
    volumes:
      - mongo-data:/data/db
    networks:
      - tasks-network

  tasks-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasks-backend
    ports:
      - "8091:8091"
    environment:
      - SERVER_PORT=8091
      # Передаем логин и пароль в строке подключения (URI)
      # Имя переменной должно совпадать с тем, что написано в application.properties
      - MONGO_URI=mongodb://muser:mpass@mongodb:27017/tasksdb?authSource=admin

    depends_on:
      - mongodb
    networks:
      - tasks-network

volumes:
  mongo-data:

networks:
  tasks-network:
    driver: bridge