apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tasks-virtual-service
spec:
  hosts:
    - "*"
  gateways:
    - app-gateway # 👈 НАМЕРТВО СВЯЗЫВАЕМ С НАШИМ GATEWAY
  http:
    - match:
        - uri:
            prefix: /tasks # 1. Если во внешнем адресе написано /tasks...
      rewrite:
        uri: /api/v1/tasks # 2. МАГИЯ: Заменяем префикс перед отправкой в Java!
      route:
        - destination:
            host: tasks-service # ...то Istio шлет запрос на ваш K8s Service
            port:
              number: 8091 # Внутренний порт вашего Java-приложения
