apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifications-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-mongodb-deployment # 👈 Уникальное имя
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-mongodb # 👈 Своя метка
  template:
    metadata:
      labels:
        app: notifications-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: rootadmin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: supersecretpassword
            - name: MONGO_INITDB_DATABASE
              value: notificationsdb
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: notifications-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-mongodb-service # 👈 DNS-имя для user-service приложения
spec:
  ports:
    - port: 27017
  selector:
    app: notifications-mongodb
